require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/extra_images", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # ExtraImage. As you add validations to ExtraImage, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      ExtraImage.create! valid_attributes
      get extra_images_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      extra_image = ExtraImage.create! valid_attributes
      get extra_image_url(extra_image)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_extra_image_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      extra_image = ExtraImage.create! valid_attributes
      get edit_extra_image_url(extra_image)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new ExtraImage" do
        expect {
          post extra_images_url, params: { extra_image: valid_attributes }
        }.to change(ExtraImage, :count).by(1)
      end

      it "redirects to the created extra_image" do
        post extra_images_url, params: { extra_image: valid_attributes }
        expect(response).to redirect_to(extra_image_url(ExtraImage.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new ExtraImage" do
        expect {
          post extra_images_url, params: { extra_image: invalid_attributes }
        }.to change(ExtraImage, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post extra_images_url, params: { extra_image: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested extra_image" do
        extra_image = ExtraImage.create! valid_attributes
        patch extra_image_url(extra_image), params: { extra_image: new_attributes }
        extra_image.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the extra_image" do
        extra_image = ExtraImage.create! valid_attributes
        patch extra_image_url(extra_image), params: { extra_image: new_attributes }
        extra_image.reload
        expect(response).to redirect_to(extra_image_url(extra_image))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        extra_image = ExtraImage.create! valid_attributes
        patch extra_image_url(extra_image), params: { extra_image: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested extra_image" do
      extra_image = ExtraImage.create! valid_attributes
      expect {
        delete extra_image_url(extra_image)
      }.to change(ExtraImage, :count).by(-1)
    end

    it "redirects to the extra_images list" do
      extra_image = ExtraImage.create! valid_attributes
      delete extra_image_url(extra_image)
      expect(response).to redirect_to(extra_images_url)
    end
  end
end
